name: "Nish"
description: "Software Engineer / Human-Computer Interaction Enthusiast"
about: "As a software engineer, I am passionate about building easy-to-use products. I have a keen interest in Human-Computer Interaction and value bridging the gap between technology and people."

projects:
  - title: "ForceIt"
    description: "ForceIt is an experimental body-based interaction system for ambient spaces. The project proposes an interaction model where a user’s body movement is captured and translated into visual physical effects in a virtual environment."
    tech: ["Java", "Kinect"]
    github: "https://github.com/nshmdayo/forceit"
    url: ""
